# Generated by Django 4.1.3 on 2022-12-23 04:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=80)),
                ('news_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
